### ISSUE TITLE
nsfw blocker stops blocking pages after a few retries

### ISSUE THREAD

**Issue by evoIutionevotv** [DestroyPorn/DestroyPorn#4]
![image](https://user-images.githubusercontent.com/123554894/215149738-571c4b65-f823-42b3-a617-e0bec0fa81c5.png)
It completely stopped blocking all nsfw pages after I tried to visit them multiple times

**Comment by thejimi** [comment]
You're running DestroyPorn on a old version, maybe try updating?

**Comment by evoIutionevotv** [comment]
yea i guess that was the culprid thx
