### ISSUE TITLE
Extension doesn't redirect tab when it's triggered, instead creating a new one

### ISSUE THREAD

**Issue by SparklingWaterBurns** [DestroyPorn/DestroyPorn#6]
**Description of the bug:**
Whenever you visit a pornography website, The extension detects it, but doesn't redirect the tab to the popup. instead, it creates a new tab and lets the user freely browse the last tab.
My computer is a Acer Chromebook 315 with a Intel processor, running ChromeOS 109
**Screenshots:**
![Screenshot 2023-01-27 7 03 18 PM](https://user-images.githubusercontent.com/110859540/215233663-849995b9-5915-479e-bc40-90b132fa12da.png)

**Web Browser:**
Chrome 109 on ChromeOS
**Manifest version:**
3

**Comment by thejimi** [comment]
Doesnt it close the pornography site?

**Comment by SparklingWaterBurns** [comment]
No, it doesn't. it only creates a new tab instead.
`chrome.tabs.update`, `chrome.tabs.remove`, and `location.replace` appears to not be working either.
![Screenshot 2023-01-28 11 44 08 PM](https://user-images.githubusercontent.com/110859540/215307707-39582b65-368f-4592-a90d-ea16efcb66ed.png)
You can use an async function to get the current tab and interact with it.
Manifest V3 Code snippet from Chrome Docs:
```
async function getCurrentTab() {
  let queryOptions = { active: true, lastFocusedWindow: true };
  // 'tab' will either be a 'tabs.Tab' instance or 'undefined'.
  let [tab] = await chrome.tabs.query(queryOptions);
  return tab;
}
```

[The docs page here](https://developer.chrome.com/docs/extensions/reference/tabs/)




,

**Comment by thejimi** [comment]
This is the function we already use, maybe try updating the extension?
