### ISSUE TITLE
[BUG] Random Message Pop-ups appearing on random sites.

### ISSUE THREAD

**Issue by evoIutionevotv** [DestroyPorn/DestroyPorn#7]
**Description of the bug:**
When visiting ANY site, a couple of these annoying popups will appear.
**Screenshots:**
![image](https://user-images.githubusercontent.com/123554894/215265178-783a17fb-788e-40e1-befc-ab745ab5f16a.png)
**Web Browser:**
Edge Chromium 109.0.1518.70
**Manifest version:**
3

**Comment by thejimi** [comment]
It was a test function in Alpha 1.0.2, please update the extension to the newest version.
